### ISSUE TITLE
M1 Mac error compiling raisimGymTorch

### ISSUE THREAD

**Issue by chengxuxin** [raisimTech/raisimLib#221]
I successfully compiled the raisimLib and get examples and Unity GUI working on an M1 mac.
However when I tried to compile raisimGymTorch by "python setup.py develop", I got "fatal error: 'omp.h' file not found". 
I have installed OpenMPI by "brew install libopenmp"
Any insights on how to resolve this?

```zsh
(raisim) cxx@MBP raisimGymTorch % python setup.py develop
running develop
/Users/cxx/miniforge3/envs/raisim/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Users/cxx/miniforge3/envs/raisim/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing raisim_gym_torch.egg-info/PKG-INFO
writing dependency_links to raisim_gym_torch.egg-info/dependency_links.txt
writing requirements to raisim_gym_torch.egg-info/requires.txt
writing top-level names to raisim_gym_torch.egg-info/top_level.txt
reading manifest file 'raisim_gym_torch.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'raisim_gym_torch.egg-info/SOURCES.txt'
running build_ext
-- pybind11 v2.6.2 
-- raisim:
--   Version: 1.1.0
--   Includes: /Users/cxx/Projects/raisim/raisimLib/raisim/m1/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
raisim os m1
raisim arch arm64
building with correct lib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/cxx/Projects/raisim/raisimLib/raisimGymTorch/build/temp.macosx-11.0-arm64-3.9
Consolidate compiler generated dependencies of target rsg_anymal
[ 33%] Building CXX object CMakeFiles/rsg_anymal.dir/raisimGymTorch/env/raisim_gym.cpp.o
clang: warning: argument unused during compilation: '-mno-avx2' [-Wunused-command-line-argument]
In file included from /Users/cxx/Projects/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/raisim_gym.cpp:10:
/Users/cxx/Projects/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/VectorizedEnvironment.hpp:10:10: fatal error: 'omp.h' file not found
#include "omp.h"
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/rsg_anymal.dir/raisimGymTorch/env/raisim_gym.cpp.o] Error 1
make[1]: *** [CMakeFiles/rsg_anymal.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/cxx/Projects/raisim/raisimLib/raisimGymTorch/setup.py", line 68, in <module>
    setup(
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cxx/Projects/raisim/raisimLib/raisimGymTorch/setup.py", line 38, in run
    self.build_extension(ext)
  File "/Users/cxx/Projects/raisim/raisimLib/raisimGymTorch/setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/Users/cxx/miniforge3/envs/raisim/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j2']' returned non-zero exit status 2.
```

**Comment by jhwangbo** [comment]
I am aware of this issue. Ill look into it today

**Comment by chengxuxin** [comment]
Any updates ?

**Comment by jhwangbo** [comment]
I spent quite some time digging into this issue. I managed to compile it for m1 but found another big issue.

https://www.anaconda.com/blog/apple-silicon-transition

Python is not well supported for m1 now. There are tricks that this link mentions but all of them look like a temporary solution to me. So I'll leave this issue open until anaconda and python developers provide a better solution.

**Comment by chengxuxin** [comment]
Thanks for your efforts! Looks like x86 linux is a better option for now.

**Comment by chengxuxin** [comment]
> I spent quite some time digging into this issue. I managed to compile it for m1 but found another big issue.
> 
> https://www.anaconda.com/blog/apple-silicon-transition
> 
> Python is not well supported for m1 now. There are tricks that this link mentions but all of them look like a temporary solution to me. So I'll leave this issue open until anaconda and python developers provide a better solution.

Can I ask what the workaround is to successfully compile raisimGymTorch?

**Comment by jhwangbo** [comment]
`brew install libomp`. Then download the files again here https://mac.r-project.org/openmp/. Include `omp.h` in the raisimLib cmake.
You can probably manually point the brew libomp version but I haven't tried it.

**Comment by EasyPaperSniper** [comment]
Hi,
The issue can be solved by:
First, install libomp:
`brew install libomp`

Then, in cmakelist.txt add the following lines to locate the OMP file:
'set(OPENMP_INCLUDE_DIRS "/opt/homebrew/Cellar/libomp/13.0.1/include")'
'set(OpenMP_C_FLAGS " -Xpreprocessor -fopenmp -lomp -lgomp ")'
'set(OpenMP_CXX_FLAGS " -Xpreprocessor  -fopenmp")'

Also, add ${OPENMP_INCLUDE_DIRS} to the 'target_include_directories':
`target_include_directories(${subdir} PUBLIC ${EIGEN3_INCLUDE_DIRS} ${OPENMP_INCLUDE_DIRS} ${RAISIMGYM_ENV_DIR}/${subdir} ${CMAKE_CURRENT_SOURCE_DIR}/raisimGymTorch/env)`

This should solve the issue.

**Comment by EasyPaperSniper** [comment]
@jhwangbo 
I built the raisimGymTorch without issue in my M1 Macbook. However, when I tried to run the runner.py, it didn't work as I expected. Here is the error:
`(raisim) tianyuli@Tianyus-MacBook-Air raisimGymTorch % conda run -n raisim --no-capture-output --live-stream python /Users/tianyuli/Documents/research_project/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py
Traceback (most recent call last):
File"/Users/tianyuli/Documents/research_project/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 2, in <module>  from raisimGymTorch.env.bin.rsg_anymal import RaisimGymEnv
ImportError:dlopen(/Users/tianyuli/Documents/research_project/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/bin/rsg_anymal.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_dispatch_init_4'`

Do you have any idea about this? Do you think it's related to OpenMP?
Thank you!

**Comment by jhwangbo** [comment]
@EasyPaperSniper 
Such errors often occur when you build the binary for different architectures. I guess two possibilities
1. you are using x86-built python (using rosetta probably) and try to read raisimGymTorch built for m1.
2. you are using m1-built python and try to read raisimGymTorch built for x86
This is where I stuck. To run python built for m1, you have to use conda-forge or other tricks (symbol not found in flat namespace '___kmpc_dispatch_init_4'). There is no clean solution that I know of

**Comment by EasyPaperSniper** [comment]
@jhwangbo 
Thank you for your help. I solved the problem, by adding these two lines in cmakelist:
`find_package(OpenMP REQUIRED)'
'target_link_libraries(${subdir} PRIVATE OpenMP::OpenMP_CXX)`
It seems macos has some troubles finding the package

**Comment by jhwangbo** [comment]
How do you use your python? Do you use conda-forge?

**Comment by EasyPaperSniper** [comment]
I'm actually using miniconda

**Comment by jhwangbo** [comment]
I am curious how fast the ANYmal example runs on the m1 CPU. What is your average iteration time if you turn off all other applications?

**Comment by EasyPaperSniper** [comment]
I'm using Macbook Air with M1 chip and 8g ram,
It runs the ANYmal example at around 46000 fps. Not sure how it performs compared to other devices. Really looking forward to the performance of the new Mac Studio.

**Comment by jhwangbo** [comment]
My system is AMD 3950x + RTX2070. I get 170k fps.

**Comment by EasyPaperSniper** [comment]
Yeah, your system looks better, let me see if I can test with a nice M1 device.  3950 has 16 cores, the CPU itself is more expensive than my laptop.  Mine is 8 core and the laptop has no fan(I basically just used it for debugging). There are some reports that mention the multi-core performance of M1 is not that excellent, not sure if that affects the performance.

**Comment by EasyPaperSniper** [comment]
I restart my laptop, now it's around 50k fps. Do you think the GPU part also affects the speed? Since pytorch does not have GPU acceleration for M1, the M1 chip has to do simulation as well as the PPO update.

**Comment by jhwangbo** [comment]
I didnt know that pytorch has no gpu acceleration for m1. That probably explains its slow speed...

**Comment by EasyPaperSniper** [comment]
From your experience, do you think an M1 machine like Mac Studio would be better for RaisimGymTorch than a standard desktop for example 3960x + RTX3080?

**Comment by jhwangbo** [comment]
Raisim runs much faster on m1 machines. But pytorch will be much slower. Lets wait until they support m1 gpus. Then i expect it to be much faster than a typical x86 setup.
