### ISSUE TITLE
raisimGymTorch runner.py example running into PermissionError

### ISSUE THREAD

**Issue by kuenem** [raisimTech/raisimLib#447]
Hello,
When I try to run the runner.py raisimGymtorch example an permission error occurs.
I've tryed to follow the point [How to run the example](https://raisim.com/sections/RaisimGymTorch.html).
I already run the command `python setup.py develop` but had to modify it to work for me to `sudo python3 setup.py develop`.
The output then is pretty long and finishes with `... Using /usr/lib/python3/dist-packages
Searching for zipp==3.15.0
Best match: zipp 3.15.0
Adding zipp 3.15.0 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Searching for pyasn1==0.4.8
Best match: pyasn1 0.4.8
Adding pyasn1 0.4.8 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Finished processing dependencies for raisim-gym-torch==1.1`

When I try to run `python raisimGymTorch/env/envs/rsg_anymal/runner.py` afterwards following output occurs:
```
2023-04-04 13:58:07.905357: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable 'TF_ENABLE_ONEDNN_OPTS=0'.
2023-04-04 13:58:07.931637: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-04 13:58:08.317055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/tfsa/development/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 66, in <module>
    tensorboard_launcher(saver.data_dir+"/..")  # press refresh (F5) after the first ppo update
  File "/home/tfsa/development/raisim/raisimLib/raisimGymTorch/raisimGymTorch/helper/raisim_gym_helper.py", line 29, in tensorboard_launcher
    url = tb.launch()
  File "/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard-2.12.0-py3.9.egg/tensorboard/program.py", line 316, in launch
    server = self._make_server()
  File "/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard-2.12.0-py3.9.egg/tensorboard/program.py", line 466, in _make_server
    (data_provider, deprecated_multiplexer) = self._make_data_provider()
  File "/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard-2.12.0-py3.9.egg/tensorboard/program.py", line 454, in _make_data_provider
    ingester = self._make_data_ingester()
  File "/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard-2.12.0-py3.9.egg/tensorboard/program.py", line 437, in _make_data_ingester
    ingester = self._start_subprocess_data_ingester()
  File "/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard-2.12.0-py3.9.egg/tensorboard/program.py", line 409, in _start_subprocess_data_ingester
    ingester.start()
  File "/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard-2.12.0-py3.9.egg/tensorboard/data/server_ingester.py", line 139, in start
    popen = subprocess.Popen(args, stdin=subprocess.PIPE)
  File "/home/tfsa/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/tfsa/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/tfsa/anaconda3/lib/python3.9/site-packages/tensorboard_data_server-0.7.0-py3.9-linux-x86_64.egg/tensorboard_data_server/bin/server'
```
Here nothing change if I use python3 instead of python.
I found some tips stating that server beeing a folder instead of a file may be the cause but I checked it and server is a file.

**Comment by jhwangbo** [comment]
This seems like tensorboard issue. I don't know why this happens but comment the line 66 in runner.py then it will work. You can manually launch the tensorboard session.
There are a few answers to this issue in stackoverflow. But I cannot tell you the real cause without accessing your computer...

**Comment by jhwangbo** [comment]
that line launches the tensorboard. Probably there is something wrong with your tensorboard installation
