### ISSUE TITLE
RuntimeError: The size of tensor a (10) must match the size of tensor b (12) at non-singleton dimension 0

### ISSUE THREAD

**Issue by kuenem** [raisimTech/raisimLib#455]
I'm currently trying to use RaisimGymTorch and modified the Enviroment to use my .urdf file.
When I try to run the runner.py file I get following Output with an ERROR message:
```
[2023:04:24:08:17:24 RaisimServer.hpp:226] Connection to 12 is established

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784


NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

ERROR:tensorboard:Failed to load plugin BasicLoader.load; ignoring it.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/backend/application.py", line 124, in TensorBoardWSGIApp
    plugin = loader.load(context)
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/plugins/base_plugin.py", line 362, in load
    return self.plugin_class(context)
  File "/home/tfsa/.local/lib/python3.8/site-packages/torch_tb_profiler/plugin.py", line 60, in __init__
    self._cache = io.Cache(self._temp_dir)
  File "/home/tfsa/.local/lib/python3.8/site-packages/torch_tb_profiler/io/cache.py", line 17, in __init__
    self._manager = mp.Manager()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
[RAISIM_GYM] Tensorboard session created: http://localhost:6006/
Visualizing and evaluating the current policy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tfsa/development/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_lh40/runner.py", line 140, in <module>
    actor.distribution.enforce_minimum_std((torch.ones(12)*0.2).to(device))
  File "/home/tfsa/development/raisim/raisimLib/raisimGymTorch/raisimGymTorch/algo/ppo/module.py", line 131, in enforce_minimum_std
    new_std = torch.max(current_std, min_std.detach()).detach()
RuntimeError: The size of tensor a (10) must match the size of tensor b (12) at non-singleton dimension 0
ERROR:tensorboard:Failed to load plugin BasicLoader.load; ignoring it.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/backend/application.py", line 124, in TensorBoardWSGIApp
    plugin = loader.load(context)
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/plugins/base_plugin.py", line 362, in load
    return self.plugin_class(context)
  File "/home/tfsa/.local/lib/python3.8/site-packages/torch_tb_profiler/plugin.py", line 60, in __init__
    self._cache = io.Cache(self._temp_dir)
  File "/home/tfsa/.local/lib/python3.8/site-packages/torch_tb_profiler/io/cache.py", line 17, in __init__
    self._manager = mp.Manager()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
[RAISIM_GYM] Tensorboard session created: http://localhost:6006/
Visualizing and evaluating the current policy
Traceback (most recent call last):
  File "/home/tfsa/development/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_lh40/runner.py", line 140, in <module>
    actor.distribution.enforce_minimum_std((torch.ones(12)*0.2).to(device))
  File "/home/tfsa/development/raisim/raisimLib/raisimGymTorch/raisimGymTorch/algo/ppo/module.py", line 131, in enforce_minimum_std
    new_std = torch.max(current_std, min_std.detach()).detach()
RuntimeError: The size of tensor a (10) must match the size of tensor b (12) at non-singleton dimension 0
```

What should I change to avoid this ERROR?

**Comment by kuenem** [comment]
I only changed the robot. So I tried to use my own model and not the anymal anymore.
I only changed 
https://github.com/raisimTech/raisimLib/blob/942e180a71bd41e75a00a8d095597e744b21aca9/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/Environment.hpp#L25
to my .urdf file and this line
https://github.com/raisimTech/raisimLib/blob/942e180a71bd41e75a00a8d095597e744b21aca9/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/Environment.hpp#L41
that it fits my standard configuration.
I don't changed anything beside this.

**Comment by jhwangbo** [comment]
You have to set up the action and observation yourself. You should read the Environment.hpp file and understand what it means. The code is just 160 lines.
